### ISSUE TITLE
BulkTranslate speed

### ISSUE THREAD

**Issue by yznts** [mind1949/googletrans#1]
Hey!
First of all, thank you for awesome package.

It's more a question rather than an issue.

I have a case, when I need to translate near 540 strings at once. There are a lot of info.
When I'm trying to translate, it takes near 30-40 seconds to process that all.
Questions is, it's related to network/API limitations, or library implementation?

I found a better way, that just works in my case. Joining strings into one with separator, translating by chunks (to bypass length limits, if any of them exist) and splitting translated text back with the same separator. It takes near 1 second, instead of 30-40.

**Comment by mind1949** [comment]
@yuriizinets Thanks for your question .

> I have a case, when I need to translate near 540 strings at once. There are a lot of info.
> When I'm trying to translate, it takes near 30-40 seconds to process that all.
> Questions is, it's related to network/API limitations, or library implementation?

To be honest, I am not satisfied with the current implementation of BulkTranslate. In the future, I will adopt a more appropriate way to implement BulkTranslate. Currently it is more suitable as a pipeline stage rather than batch translation.

> I found a better way, that just works in my case. Joining strings into one with separator, >translating by chunks (to bypass length limits, if any of them exist) and splitting translated text back with the same separator. It takes near 1 second, instead of 30-40.

Although it will affect the accuracy of translation, it is still a good strategy.Thank you for your suggestion.

When I am finished modifying BulkTranslate, I will notify you as soon as possible .

**Comment by yznts** [comment]
I’ll review that BulkTranslate when it would be some free time. Maybe translations processing in goroutines will help. It would be nice to get rid of my translation method in the project and do it in more right way 😄
Also, pipeline approach is nice, but hard to use when I just want to translate slice of strings. Maybe I’ll propose 2 different methods for that with PR a bit later

**Comment by mind1949** [comment]
🤝
